### ISSUE TITLE
Update NextJS to version 9.4

### ISSUE THREAD

**Issue by jamessspanggg** [GiftForGood/website#85]
# Feature request

## Is your feature request related to a problem? Please describe.

NextJS has new benefits in it's latest version 9.4. 
The benefits:
- easy import of `.env`
- does not require to import fetch
- fast refresh

## Describe the solution you'd like

Update NextJS version

## Describe alternatives you've considered

N.A.

## Additional context

N.A.

**Comment by kohchihao** [comment]
The benefits of using `NextJS 9.4` 
- Faster Refresh without losing state (https://nextjs.org/blog/next-9-4#fast-refresh)
- Using of `.env` directly without messing with `next.config.js` (https://nextjs.org/blog/next-9-4#new-environment-variables-support)
- Do not need to install `isomorphic-fetch` anymore. `fetch` comes preinstalled now. However, this doesn't affect us because we are using `axios`
- `Absolute imports`: Currently we are importing alot of our own submodules via "../../../../../" which is horrible! The new NextJS 9.4 allows us to import direct by "src/components/login/modules/FileA" directly.

**Comment by jamessspanggg** [comment]
Upgraded to 10.0.0
